### ISSUE TITLE
How to expire a key?

### ISSUE THREAD

**Issue by theronic** [luin/ioredis#1117]
`expire` seems to be [undocumented](https://github.com/luin/ioredis/blob/master/API.md).

**Comment by osukaa** [comment]
`ioredis` doesn't document the commands available from the connected Redis instance.  They're sourced from [redis-commands](https://github.com/NodeRedis/redis-commands).

**Comment by besoeasy** [comment]
redis.set(besoeasy, 'value', 'ex', 9200)


expires 9200 seconds

**Comment by dickeylth** [comment]
> redis.set(besoeasy, 'value', 'ex', 9200)
> 
> expires 9200 seconds

It's friendly to add the comment to the readme, for beginners it's really confusing what the fourth param means without comment in the example.

```
...
// All arguments are passed directly to the redis server:
redis.set("key", 100, "EX", 10);       <- 10 stands for what?
```

**Comment by luin** [comment]
@dickeylth Good point on the potential confusion but since we're mapping Redis commands directly to JavaScript methods, we should suggest users refer to the official documentation on Redis website for usage details. An update to README to reflect the idea may be helpful. I'm closing this issue but PRs about documentation implementation is welcome.
