### ISSUE TITLE
Add delay in option for a MOVED response

### ISSUE THREAD

**Issue by ohadisraeli** [luin/ioredis#1189]
When a MOVED response is received from the server currently the client supports only the maxRedirections option.
Adding a delay option can prevent a ping pong effect until the cluster has the new sharding state stabilized.

I think that if we can have the MOVED response to be pushed to a delayed queue like the way some of the other errors are handled as seen below:

        if (errv[0] === 'MOVED' || errv[0] === 'ASK') {
            handlers[errv[0] === 'MOVED' ? 'moved' : 'ask'](errv[1], errv[2]);
        }
        else if (errv[0] === 'TRYAGAIN') {
            this.delayQueue.push('tryagain', handlers.tryagain, {
                timeout: this.options.retryDelayOnTryAgain
            });
        }

**Comment by luin** [comment]
Hi, I think cases are rare in which the delay option is useful because most commonly, the correct slot target will be returned together with the `MOVED` error so simply redirect the command to that target would be efficient. This process follows the official spec: https://redis.io/topics/cluster-spec#redirection-and-resharding.

However, I can see how the delay option helps for the cases you mentioned as it "can prevent a ping pong effect" but I'd like to understand your specific case and what would you use as the value of the option.

**Comment by ohadisraeli** [comment]
In our case, we are experiencing under load that we get a MOVED response but the other node has not been yet updated therefore it again redirects to the original node and therefore the ping pong effect. I was thinking of the ability to support a delay parameter. Maybe a constant small number such as 50 might do the trick (currently, we see that the message is sent in about 2ms)

**Comment by ohadisraeli** [comment]
Maybe the change that I have applied in my environment will help to get a better understanding, the original code is commented:

    if (errv[0] === 'MOVED' || errv[0] === 'ASK') {
      // handlers[errv[0] === "MOVED" ? "moved" : "ask"](errv[1], errv[2]);
      this.delayQueue.push("moved",handlers.moved.bind(null, errv[1], errv[2]),
        {
          timeout: this.options.retryDelayOnMoved(this.options.maxRedirections + 1 - ttl.value)
        }
      );

**Comment by luin** [comment]
Closed via #1254
