### ISSUE TITLE
bitop command is not supported

### ISSUE THREAD

**Issue by tlfu12344gmail** [luin/ioredis#1212]
bitop command is not supported?

**Comment by simonprickett** [comment]
@tlfu12344gmail which ioredis version are you using, I'm able to make this work in 4.17.3 using the example `bitop` command sequence from the bitop command page on redis.io (https://redis.io/commands/bitop).

Working example code:

```javascript
const Redis = require('ioredis');
const redis = new Redis({
  host: '127.0.0.1',
  port: 6379
});

const redisDemo = async () => {
  await redis.set('key1', 'foobar');
  await redis.set('key2', 'abcdef');
  await redis.bitop('and', 'dest', 'key1', 'key2');
  const r = await redis.get('dest');
  console.log(r);
};

redisDemo();
```

Output of the above:

```
`bc`ab
```

The only other thing I would suggest checking is that your Redis version supports the bitop command, but it's been in there since 2.6 and that's old now, so I'm guessing that's not the case.
