### ISSUE TITLE
retryAttempts exceeding maxRetriesPerRequest, goes on reconnecting indefinitely for new Redis({options_come_here})

### ISSUE THREAD

**Issue by hamvisa** [luin/ioredis#1351]
Trying to establish new Redis connection using ioredis. Once the server goes down, the client is not ending after maxRetriesPerRequest. retryStrategy is called indefinitely.

**Comment by luin** [comment]
Hey @hamvisa. The two options are not related. `retryStrategy` will be called every time the connect attempt is failed. You may want to return a non-number value to discard further attempts. `maxRetriesPerRequest` is to single command instead of the whole connection. A command will be rejected when retry attempts exceed `maxRetriesPerRequest` but the whole connection may still retry based on the return value of `retryStrategy`.
