### ISSUE TITLE
[Question] Does ioredis support redis modules?

### ISSUE THREAD

**Issue by banchanKiro** [luin/ioredis#1461]
Im quit new to redis, and I had been finding a way to define custom functions to atomically operate redis, and I saw that [Redis Modules](https://redis.com/blog/writing-redis-modules/) are a much better way than using lua scripting.

Does ioredis support the usage of these modules, and if so how does one go about calling the custom module?

**Comment by crysislinux** [comment]
It's yes and no. Ioredis doesn't support it natively but provides two APIs for you to extend it. 

`addBuiltinCommand` and `createBuiltinCommand`.

Here is an example for `createBuiltinCommand`:
https://github.com/luin/ioredis/issues/1205

here is for `addBuiltinCommand`:
https://github.com/luin/ioredis/issues/1464

`addBuiltinCommand` could be the best option since the added commands are on the Redis instance. But all Redis modules have command prefixes, which makes it a bit wired to call the new commands as https://github.com/luin/ioredis/issues/1464 said.

**Comment by luin** [comment]
I'd suggest using `redis.call()` (e.g. https://github.com/luin/ioredis/blob/main/examples/module.js) but we probably going to add official typings for it.

**Comment by luin** [comment]
Merged into #1489
