### ISSUE TITLE
Missing copy command

### ISSUE THREAD

**Issue by BalazsSevecsek** [luin/ioredis#1537]
Hello,

I'd like to use the copy command from redis within the same database, but I noticed ioredis is missing it from the list of available commands. [copy command link in docs](https://www.redis.io/commands/copy) Why is that?

If it won't be implemented anytime in the future, how can I use it in some way to stay compatible with ioredis? I'd like to embed it in a multi() call.

Thanks,
Sevi

**Comment by luin** [comment]
Hey @BalazsSevecsek 👋 ,

`copy` is supported. The issue is `@types/ioredis` doesn't provide a declaration for it. So I think for now you can use `// @ts-expect-error` to bypass the error and will be able to remove it once v5.0.0 becomes stable since v5.0.0 provides official TypeScript declaration (should happen in two weeks).

**Comment by BalazsSevecsek** [comment]
Thanks, that cleared it all up :)
