### ISSUE TITLE
Status flag not following the actual client status

### ISSUE THREAD

**Issue by Baptiste-Garcin** [luin/ioredis#1561]
The `status` flag does not follow the real status of the client.

```typescript
const client = new IORedis()

const func = async function() {
  await client.connect()
  console.log(client.status) // ready

  await client.quit()
  console.log(client.status) // ready
}

func()
 .catch((err) => console.error(err))
```

It's really not convenient.

**Comment by luin** [comment]
Hey @Baptiste-Garcin 👋 

`Redis#quit()` is a normal command that will be resolved as long as the Redis server returns a reply, and the connection will be disconnected asynchronously. So In the second console.log, the connection hasn't been disconnected yet.

Not sure about your use case, but to get reliable status, you can listen to the "close" or "end" event.

**Comment by Baptiste-Garcin** [comment]
Hi @luin

I am still confused… How can `quit` can be asynchronous and still, the promised it returns does not resolve at the end of the operation. The operation ends after an event is fired. So at the end why should I await `quit` ?

**Comment by luin** [comment]
Yeah, I got your point. The thing is, ioredis doesn't do anything special to `quit`: it's just a normal Redis command as `set`, `get`, and others. So what happens when you call `redis.quit()`:

1. ioredis sends a `QUIT` command to the server.
2. The server receives the command and replies "OK".
3. ioredis gets the reply, and this is the point the promise is resolved.
4. At the same time as step 3, the server waits for all pending replies to be sent to the client (https://redis.io/commands/quit/), and once this is done, the server closes the connection. This is why the operation is asynchronous.

You can handle this on the app side instead:

```js
const gracefullyDisconnect = async (redis) => {
  if (redis.status === "end") {
    return;
  }

  return new Promise((resolve, reject) => {
    redis.once('end', () => {
      resolve();
    });

    redis.quit().catch(reject);
  });
}
```

**Comment by Baptiste-Garcin** [comment]
ok, thanks for the snippet. I assume `redis.connect()` work the same way ?
