### ISSUE TITLE
Are there some disadvantages of enabling auto pipelining?

### ISSUE THREAD

**Issue by pasha-vuiko** [luin/ioredis#1608]
Are there some disadvantages of enabling auto pipelining? 

Auto pipelining option can speed up IoRedis up to 2 times, does some catch exists here ? Or I can be 100% calm when enabling the option on production?

**Comment by em** [comment]
1- I run into issues with it all the time using upstash as there are hard limits on command size and it's counted as one command big command.
2- You won't get a response back until all commands in the pipeline have finished. There are situations where you might run many things in parallel that each have separate pieces of work to do. The collection of second stages will be blocked by the collection of first stages with autopipeline on.

e.x:

```
let a = doA().then(doB)
let b = doC().then(doD)
```

doB and doD are going to be blocked by BOTH doA and doC, instead of just one respectively as they would be without autopipelining.

**Comment by pasha-vuiko** [comment]
Great, thank you for explaining!
