### ISSUE TITLE
Connect to password required cluster failed

### ISSUE THREAD

**Issue by nichliu** [luin/ioredis#182]
Redis server v=3.0.4
ioredis version: 1.9.1
NodeJS: 4.2.1
Ubuntu: 14.04

var redis = new Redis.Cluster([{
    port: 6379,
    host: "10.240.xxx.xxx",
    password: "xxxxxxxx"
},{
    port: 6379,
    host: "10.240.xxx.xxx",
    password: "xxxxxxxx"
}]);

got error message
Error Error: Failed to refresh slots cache.

**Comment by luin** [comment]
Currently there's no support for connecting to a password-protected cluster. It's not straightforward to implement this feature since the nodes may have different passwords. Although passwords can be specified when you creating a `Redis.Cluster` instance (like your example), ioredis may auto-detect more nodes in the cluster that have different passwords.

According to this topic: https://groups.google.com/d/msg/redis-db/Z8lMxTfDct8/Rny9BIK9xGYJ, it seems that setting passwords to the cluster may not be a best practice, and redis-trib.rb also doesn't support it.

What do you suggest given the above thoughts?

**Comment by nichliu** [comment]
Thx, That make sense, I can use it as internal servers without password.

But I still think add password support for cluster will more secure, even you can require all Redis cluster nodes to use same password. 

Thank you for your help.

**Comment by luin** [comment]
Hi, this feature is implemented and shipped in 1.10.0. Refer to https://github.com/luin/ioredis#password for details. Let me know whether this works for you :laughing:

**Comment by nichliu** [comment]
works very good for me.

Thank you
