### ISSUE TITLE
You should redo the benchmark with latest node_redis

### ISSUE THREAD

**Issue by thelinuxlich** [luin/ioredis#186]
Since version 2.2.0 they are claiming huge performance increase: https://github.com/NodeRedis/node_redis/releases/tag/v.2.2.0

**Comment by luin** [comment]
People already have posted results with the newest node_redis version here: https://github.com/luin/ioredis/issues/25. In my computer (iMac 5k), there's not much difference comparing with the result shows in the readme when I use the newer node_redis (ioredis is still 50% faster). 

I noticed people got different results in their computers/servers. However, IMO the difference is trivial since both two libraries are very fast, and neither node_redis nor ioredis will become the bottleneck in most applications.

Anyway I'll just remove the benchmark section from the README as most people shouldn't care about that, and if someone really does, they should run the benchmarks in their servers themselves.

**Comment by zhuangya** [comment]
> I noticed people got different results in their computers/servers. However, IMO the difference is trivial since both two libraries are very fast, and neither node_redis nor ioredis will become the bottleneck in most applications.

make sense
