### ISSUE TITLE
.getBuffer() does not work in a pipeline

### ISSUE THREAD

**Issue by jonathanong** [luin/ioredis#223]
```js
// ok
client.setBuffer('test', new Buffer('00ff44', 'hex'))
// ok
client.getBuffer('test')

client.multi()
  .getBuffer('test')
  .exec()
// => [ null, '\u0000�D' ]
```

**Comment by luin** [comment]
Technically the result of your `get` command within a transaction is `QUEUED` instead of `0x00ff44` (which is the result of `exec` command). So if you pass a callback to the `getBuffer` command, you will get a buffer, which value is `QUEUED`:

```javascript
redis.multi().getBuffer('foo', function (_, res) {
  console.log(res.toString()); // res is a buffer, value is 'QUEUED'
}).exec();
```

I just released a new version to supports `execBuffer` for transactions:
```javascript
redis.multi().get('foo').execBuffer();
```

It's a little misleading of course since the interface between transaction and pipelining are similar. I'm planning to rewrite this part to make `client.multi().getBuffer('test').exec()` returns a buffer and deprecate `execBuffer`. However I'll do it in the next major version since it breaks BC.

Let me know if anyone has any idea of it.
