### ISSUE TITLE
Cluster isn't ready and enableOfflineQueue options is false, with defaults

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#233]
Hey,

We are using `ioredis` for quite some time now and its great.

We noticed that sometimes (Can't reproduce really) we have logs of `Cluster isn't ready and enableOfflineQueue options is false`, even though we are using the default settings of `enableOfflineQueue` which is `true`.

Any ideas?

**Comment by shaharmor** [comment]
I think it happens when the library didn't finish loading and we are already sending commands to it

**Comment by luin** [comment]
Sorry for my late response. It's really strange since this error only emits when the `enableOfflineQueue` is `false`: https://github.com/luin/ioredis/blob/master/lib/cluster.js#L479-L486.
What do you mean by `the library didn't finish loading`? Are you sending commands before setting `cluster.options.enableOfflineQueue = true`?

**Comment by shaharmor** [comment]
I'm not setting `cluster.options.enableOfflineQueue = true` at all as it is the default, but maybe its possible that the library didn't yet set this property itself and then when its getting to the line you marked its seeing the value as undefined or something...

**Comment by luin** [comment]
I don't think it's possible since the options is defined in the `constructor` of Cluster (https://github.com/luin/ioredis/blob/master/lib/cluster.js#L64).

**Comment by shaharmor** [comment]
I actually managed to replicate it. Trying to create a simple script now

**Comment by shaharmor** [comment]
@luin found it. PR ready
