### ISSUE TITLE
Not support array value which supported by node_redis

### ISSUE THREAD

**Issue by tangxinfa** [luin/ioredis#234]
node_redis example:

    var createClient = require('redis').createClient;
    client.set('redis-array', []);    // OK, stored value is ""

ioredis example:

    var Redis = require('ioredis');
    client = new Redis();
    client.set('ioredis-array', []);  // Unhandled rejection ReplyError: ERR wrong number of arguments for 'set' command

As i test hset command also have the same problem, hopes this will fix or documention on https://github.com/luin/ioredis/wiki/Migrating-from-node_redis

**Comment by luin** [comment]
Well that's because ioredis flattens the parameters of the command, so that the following two are equal:
```javascript
client.set('redis-array', []);
client.set('redis-array');
```

And so do the following two:

```javascript
client.sadd('set', ['a', 'b', 'c']);
client.sadd('set', 'a', 'b', 'c');
```

It's a documented feature: https://github.com/luin/ioredis#basic-usage and I've pointed this out on https://github.com/luin/ioredis/wiki/Migrating-from-node_redis.

Thank you for letting me know.

**Comment by BridgeAR** [comment]
@tangxinfa this is not supported in node_redis either and was a bug, not a feature.  It was fixed in v.2.0.0.

**Comment by tangxinfa** [comment]
@luin 
Good job. I was migrated one project to use ioredis today for access redis sentinel.

@BridgeAR 
Thanks for share this information, we depends on node_redis to call toString on values, i will check our code before use new version of node_redis in other projects.
