### ISSUE TITLE
support for watch

### ISSUE THREAD

**Issue by ianjuma** [luin/ioredis#266]
Haven't seen this on the docs; does this library support watching a key, and optimistic locking with redis? Is this supported with transactions?

And if this is available; are retries built internally, when collision occurs?
have seen a reference issue; maybe update the docs to show this?

**Comment by luin** [comment]
`WATCH` command itself is supported. However users should handle retries themselves when transaction failed.

**Comment by ozomer** [comment]
It is very hard to implement the optimistic-lock pattern (1. watch 2. get 3. unwatch or do a multi-transaction) using ioredis or any other async library. "Watch" is per client, which means that if you call `watch` and while waiting for the promise a different part of your code executes a different multi-transaction, the other transaction will release the watch (and it will run/fail according to the changes in the irrelevant watched key).
In my opinion there should be an api called `redis.watchLock(...)` (i.e. not to break existing code that uses `watch(...)`), which should return a promise to a `watchClient` object. This object should keep a set of all the keys currently being watched (`watchClient._watchedKeys`), and support all the api of ioredis. Calling `watchClient.watch(...)` should add the new key to `watchClient._watchedKeys`, calling `watchClient.unwatch(...)` should remove the key, and calling `watchClient.multi(). ... .exec()/.discard()` should clean all the keys from `watchClient._watchedKeys`. Once `watchClient._watchedKeys` is empty, the `watchClient` should be marked _disabled_ and all further operations should fail.
The "locking" mechanism is applied to other parts of the code that might try to call `redis.watchLock(...)` or `redis.multi(). ... .exec()` or even `redis.multi({pipeline: false})`. These commands promises should be postponed until the `watchClient` is disabled.

This will obviously block some of the asynchronous operation, but since `watch` is per-client I don't see another way to make `watch` useful.

P.S. I am relatively new to redis, so if there is some ninja-trick to use optimistic-locking (other then using [ioredis-lock](https://www.npmjs.com/package/ioredis-lock)) please let me know.

**Comment by Pyrolistical** [comment]
yep, event loop + redis watch do not work well together. would be made easy if redis allowed named watch sets

**Comment by mstfst** [comment]
> It is very hard to implement the optimistic-lock pattern

I think that's a very good point @ozomer , and I was wondering if anyone else had this concern, like I do now.

My workaround might be to use an abstraction layer over ioredis (similar to RedisRepository in https://medium.com/@akintobiidris/using-redis-client-in-nestjs-3fe80eb91a49 - I'm using NestJS), and use request IDs to manage watched keys in that abstraction layer to ensure Redis keys are not unintentionally unwatched.

(I'm using a single ioredis client as a provider for my NestJS app)

I'm still thinking through it though.
