### ISSUE TITLE
Difference between node_redis

### ISSUE THREAD

**Issue by xavierchow** [luin/ioredis#268]
Hey, I'm migrating from node_redis and just found the following thing isn't mentioned in the [migration wiki](https://github.com/luin/ioredis/wiki/Migrating-from-node_redis).
* `hgetall` with non-existed key gets `null` with node_redis, but for ioredis it returns empty object(`{}`).

Would you have a confirmation?

**Comment by luin** [comment]
Yes, that's correct. Redis servers return an empty list instead of `null` when `hgetall` a non-existsed key, so in ioredis, an empty object is returned. The related code is here: https://github.com/luin/ioredis/blob/master/lib/command.js#L286-L295.

I added this into the wiki. Thank you for pointing this out!

**Comment by xavierchow** [comment]
thanks for quick response, closing.
