### ISSUE TITLE
Command timeout in offline queue

### ISSUE THREAD

**Issue by tzvika-m-ironsrc** [luin/ioredis#285]
When offline queue and auto reconnect are enabled, in case of a dead server (or incorrect connection parameters) the client will try to connect to the server infinitely.
In this case command promises will never get rejected or resolved.
I think there should be a timeout option (per command or globally) that after that time the promise is rejected and deleted from the queue.
If there is another feature that solves this scenario please tell me.
Thanks.

**Comment by luin** [comment]
This issue has been discussed before (https://github.com/luin/ioredis/issues/61). I tried to implement max retries option several months ago but it was a little difficult. I'll revisit this issue again since I agree that command timeout or retry limiting is pretty useful.

I'm closing this issue in favour of #61.
