### ISSUE TITLE
keyPrefix does not apply to publish/subscribe

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#306]
I was going to submit a pull request, but ioredis depends on redis-commands, and the fix is both in ioredis and redis-commands.

In redis-commands/commands.json,   subscribe/unsubscribe/psubscribe/punsubscribe should all be changed from:
```
    "keyStart": 0,
    "keyStop": 0,
    "step": 0
```

to 

```
    "keyStart": 1,
    "keyStop": 1,
    "step": 1
```

This will cause the keyPrefix to be applied to the commands sent to redis.  The next step is in parser.js - removing the keyPrefix from the channel before emitting it.

My fixes, starting at line 105 of parser.js.  Use/apply as appropriate:

```javascript
  var item, channel, count, message;
  if (this.condition.subscriber) {
    var replyType = Array.isArray(reply) ? reply[0].toString() : null;
    debug('receive reply "%s" in subscriber mode', replyType);
    switch (replyType) {
    case 'message':
      message = (this.options.keyPrefix) ? reply[1].toString().substr(this.options.keyPrefix.length) : reply[1].toString();
      if (this.listeners('message').length > 0) {
        this.emit('message', message, reply[2].toString());
      }
      if (this.listeners('messageBuffer').length > 0) {
        this.emit('messageBuffer', new Buffer(message), reply[2]);
      }
      break;
    case 'pmessage':
      var pattern = reply[1].toString();
      message = (this.options.keyPrefix) ? reply[2].toString().substr(this.options.keyPrefix.length) : reply[2].toString();
      if (this.listeners('pmessage').length > 0) {
        this.emit('pmessage', pattern, message, reply[3].toString());
      }
      if (this.listeners('pmessageBuffer').length > 0) {
        this.emit('pmessageBuffer', pattern, new Buffer(message), reply[3]);
      }
      break;
    case 'subscribe':
    case 'psubscribe':
      channel =  this.options.keyPrefix + reply[1].toString();
      this.condition.subscriber.add(replyType, channel);
      item = this.commandQueue.shift();
      if (!fillSubCommand(item.command, reply[2])) {
        this.commandQueue.unshift(item);
      }
      break;
    case 'unsubscribe':
    case 'punsubscribe':
      channel = reply[1] ? this.options.keyPrefix + reply[1].toString() : null;
      if (channel) {
        this.condition.subscriber.del(replyType, channel);
      }
      count = reply[2];
      if (count === 0) {
        this.condition.subscriber = false;
      }
      item = this.commandQueue.shift();
      if (!fillUnsubCommand(item.command, count)) {
        this.commandQueue.unshift(item);
      }
      break;
```

**Comment by luin** [comment]
This is similar to the warning message in https://github.com/luin/ioredis#transparent-key-prefixing. Since the option is `keyPrefix`, the prefix will be only applied to keys, instead of patterns and channels.

Your fix seems good to me, however I'm not sure if we should use another option (maybe `channelPrefix`) to set the prefix for channels.

**Comment by klinquist** [comment]
Makes sense... if I wanted to submit a PR, should I first to it on redis-commands?

**Comment by luin** [comment]
redis-commands/commands.json is generated by the script https://github.com/NodeRedis/redis-commands/blob/master/tools/build.js. It's just the result of `COMMAND` command, which I think we shouldn't change.

To support `channelPrefix`, we can write a argument transformer for `publish` command (we also have to pass the options to the transformer so it can know what to prefix https://github.com/luin/ioredis/blob/master/lib/command.js#L67).

However I think `channelPrefix` option is not necessary since it's not hard to be implemented by the users.
