### ISSUE TITLE
cluster: redisOptions ingored in pipeline()

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#328]
```
// conf example
redis: {
    options: {
      // attempt to fix cluster?
      keyPrefix: '{ms-users}',
      // pass this to constructor
      redisOptions: {
        // must have {}, so that the keys end up on a single machine
        keyPrefix: '{ms-users}',
        // do not use buffers
        dropBufferSupport: true,
      },
    },
  },
```

When using cluster like `new redis.Cluster(redis.hosts, redis.options)` - commands in `.pipeline()` ignores redisOptions and I have to duplicate `keyPrefix` in both root options and `redisOptions`

**Comment by luin** [comment]
Just reviewed the code, and it turns out `keyPrefix`, `dropBufferSupport` and `showFriendlyErrorStack` are the only three options that have to passed to the root options instead of `redisOptions`. It has nothing to do with pipeline that even you simply run `cluster.get('foo')`, the key will also not be prefixed (could you please confirm this?).

This is not by designed and should be considered as a bug. However fixing this bug will break BC, so I prefer to update the documentation about this and fix it in v3.0. What do you think?

**Comment by AVVS** [comment]
let me check with the tests and get back to you, fixing this in 3.0 is fine if you say that redisOptions are actually not needed for this

**Comment by AVVS** [comment]
@luin confirmed
