### ISSUE TITLE
Can't get example to exit successfully

### ISSUE THREAD

**Issue by dstitt** [luin/ioredis#335]
This simple script never exits (nodejs on linux). I'd expect it to, the equivalent script python certainly does. I *think* its due to the ioredis module hanging around and not unref'ing itself.

any clues? I'm basically stuck.

```
var Redis = require("ioredis");
var redis = new Redis();

redis.set("foo","bar"); 
redis.incr("nextid");

redis.get("nextid", function (err, result) { 
  console.log(result);
});
```

**Comment by luin** [comment]
Yes, that's because the connection is still active. Calling `redis.disconnect()` or `process.exit()` should exit the program.

Get Outlook for iOS




On Thu, Jun 16, 2016 at 9:51 PM +0800, "dstitt" <notifications@github.com> wrote:












This simple script never exits (nodejs on linux). I'd expect it to, the equivalent script python certainly does. I think its due to the ioredis module hanging around and not unref'ing itself.



any clues? I'm basically stuck.

var Redis = require("ioredis");
var redis = new Redis();

redis.set("foo","bar"); 
redis.incr("nextid");

redis.get("nextid", function (err, result) { 
  console.log(result);
});
