### ISSUE TITLE
how to use ioredis with socket.io ?

### ISSUE THREAD

**Issue by faller** [luin/ioredis#34]
I use node_redis before, and it need a 'detect_buffers' option, can you show me an example with ioreids? thank you !

**Comment by luin** [comment]
Could you give me an example where `detect_buffers` is needed?

**Comment by faller** [comment]
https://github.com/Automattic/socket.io-redis

var redis = require('redis').createClient;
var adapter = require('socket.io-redis');
var pub = redis(port, host, { auth_pass: "pwd" });
var sub = redis(port, host, { detect_buffers: true, auth_pass: "pwd" });
io.adapter(adapter({ pubClient: pub, subClient: sub }));

detect_buffers: default to false. If set to true, then replies will be sent to callbacks as node Buffer objects if any of the input arguments to the original command were Buffer objects. This option lets you switch between Buffers and Strings on a per-command basis, whereas return_buffers applies to every command on a client.

**Comment by luin** [comment]
ioredis handles binary data in a different way described [here](https://github.com/luin/ioredis#handle-binary-data) and [here](https://github.com/luin/ioredis#pubsub). `messageBuffer` should be listened instead of `message` if you want to get binary message using ioredis(https://github.com/Automattic/socket.io-redis/blob/master/index.js#L77).

**Comment by faller** [comment]
thx
