### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by luin** [luin/ioredis#347]
**What problems to solve**:
1. Currently, ioredis supports transforming arguments and replies of commands by calling `Redis.Command.setArgumentTransformer` and `Redis.Command.setReplyTransformer`. However, this will apply the transformers to the global namespace that all `Redis` instances have to apply the transformers, which could be a problem in large applications that have several instances used for different situations and purposes.
2. What's more, transformers are not flexible enough in some situations (see https://github.com/luin/ioredis/issues/319).

**How to solve the problems**:
Async hooks is a good way to solves these problems. Two types of hooks can be specified when creating new `Redis` instances: `beforeSend` and `afterFetch`, which will be invoked before sending commands to the Redis server and after any replies being fetched. A sample syntax:

``` javascript
var redis = new Redis({
  hooks: {
    beforeSend(command, args) {
      if (command.name === 'set') {
        return compress(args[1]).then(ret => args[1] = ret);
      }
    },
    afterFetch(command, replies) {
      if (command.name === 'get') {
        return uncompress(replies[0]).then(ret => replies[0] = ret);
      }
    }
  }
});
```

Since all transformers can be implemented with hooks, transformers will be removed in the next major version.

**Comment by jamesmoriarty** [comment]
@luin I would love to see this feature. In the past I've used a [memecached client](https://github.com/petergoldstein/dalli) which supported compressions for a high traffic site. 

It's important for better utilisation of:
- cache memory
- bandwidth

Often people don't realise they are saturating available bandwidth transferring large fragments.

**Comment by ozomer** [comment]
I would like to suggest a different feature that could fix the same problem: dynamically overloading the api with more functions.
The current api already provides a "Buffer" api for each function: `get(...)` has `getBuffer(...)`, `set(...)` has `setBuffer(...)`, `hget(...)` has `hgetBuffer(...)` etc. These functions allow to pack/unpack the value in two different ways: string (default) and buffer. I would like to be able to call something like:
`Redis.Command.setDynamicTransformer('Snappy', function decoder(compressedValue) { return uncompress(compressedValue); }, function encoder(uncompressedValue) { return compress(uncompresedValue); })`, that will add a third way to pack/unpack the values: `getSnappy(...)`, `setSnappy(...)`.
The encoder transformer should operate on the "values" of the function, which appear in different positions in each command - for example, in `set` the "value" appears in the second parameter, in `hset` in the third parameter, and in `mset` the "value" appears in all even parameters. Similarly, `get` returns a single value to decode and `mget` returns multiple values to decode.

This solution will allow to dynamically decide in the code whether I want to use `get`, `getBuffer`, `getSnappy` or `getMsgpack`, instead of writing the transformations in one place and having to adapt it to each command by yourself.

P.S.
It would also be great to be able to make the encoder/decoder functions return a Promise.

**Comment by cuiweiqiang** [comment]
Is there any updates for this func ?

**Comment by jonaskello** [comment]
I need to do async tranformations of the result. This looks like a good idea, any reason it is closed?

**Comment by mishaled** [comment]
@luin Was this implemented in some way?
