### ISSUE TITLE
keyPrefix vs prefix

### ISSUE THREAD

**Issue by aleemb** [luin/ioredis#359]
I just switched to this lib and was reading that there are plans to merge this with node_redis. In either case, I found that I had to rename `prefix` to `keyPrefix`. Either this could be mentioned in the migration docs or better still, renaming the key to `prefix` would make the migration a bit more seamless.

**Comment by luin** [comment]
Hi @aleemb. `keyPrefix` is first supported by ioredis, and at that time, node_redis didn't have this feature, so the migration guides didn't include it. I just revisited the guides and found out it mentioned "The options passed to the constructor are different".

As for me, `keyPrefix` is better since the prefix only applies on the keys rather than patterns and channels.

**Comment by aleemb** [comment]
> As for me, keyPrefix is better since the prefix only applies on the keys rather than patterns and channels.

I wasn't aware of this distinction, makes sense. Thanks for highlighting it.
