### ISSUE TITLE
Issue with Connection resets and Time outs.

### ISSUE THREAD

**Issue by camdenorrb** [luin/ioredis#375]
```
var http = require('http'),
    Redis = require('ioredis'),
    redis = new Redis({host: '<Snipe>', password: '<Snipe>'});

http.createServer(function(request, response) {
     response.writeHead(200, {'Content-Type': 'text/plain'});
     redis.hget('player:3064ce58-a05d-4783-86aa-c700b3e9fc66', 'Rank', function (err, result) { response.end(result); });
}).listen(4546);

process.on('uncaughtException', function(ex) {console.log(ex.stack());});
console.log('SERVER IS NOW ON! :3');
```

Node logs:

> 1|server   | SERVER IS NOW ON! :3
> 
> [STREAMING] Now streaming realtime logs for [all] processes
> 1|server   | [ioredis] Unhandled error event: Error: read ECONNRESET
> 1|server   |     at exports._errnoException (util.js:1036:11)
> 1|server   |     at TCP.onread (net.js:564:26)
> 3|server   | [ioredis] Unhandled error event: Error: read ECONNRESET
> 3|server   |     at exports._errnoException (util.js:1036:11)
> 3|server   |     at TCP.onread (net.js:564:26)
> 2|server   | [ioredis] Unhandled error event: Error: read ECONNRESET
> 2|server   |     at exports._errnoException (util.js:1036:11)
> 2|server   |     at TCP.onread (net.js:564:26)
> 1|server   | [ioredis] Unhandled error event: Error: read ETIMEDOUT
> 1|server   |     at exports._errnoException (util.js:1036:11)
> 1|server   |     at TCP.onread (net.js:564:26)
> 3|server   | [ioredis] Unhandled error event: Error: read ETIMEDOUT
> 3|server   |     at exports._errnoException (util.js:1036:11)
> 3|server   |     at TCP.onread (net.js:564:26)

**Comment by luin** [comment]
It seems to be a network problem. Are you able to connect to your redis instance via redis-cli?

**Comment by camdenorrb** [comment]
Indeed, I can. I also used Redis Desktop manager, and Jedis. So I am certain it's not my side.

**Comment by luin** [comment]
The `ECONNRESET` error means other side of the TCP conversation (Redis server or any proxy) abruptly closed its end of the connection, so it shouldn't be a problem on the ioredis side. Could you check if ioredis ran in the same network environment as RDM or Jedis? Please enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs here.

**Comment by camdenorrb** [comment]
Ok, recently my routers ethernet ports blew out. So I will need to wait about a week to test that out (Until the new router gets in). I will let you know how it goes then.

**Comment by camdenorrb** [comment]
I don't get the error when I am not in loadbalancer mode from PM2 (A process manager for NodeJs) Not sure if there is a way to fix this :C

**Comment by vhung92** [comment]
I also recently stumbled upon this issue when trying to connect to remote redis instances, here are the logs from node:

`DEBUG=ioredis:* node test.js
ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
ioredis:redis status[<sentinel-host-1>:26379]: [empty] -> connecting +4ms
ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,redis) +4ms
ioredis:redis queue command[0] -> set(cache:documents:hello,world) +1ms
ioredis:redis status[<sentinel-host-1>:26379]: connecting -> connect +64ms
ioredis:redis status[<sentinel-host-1>:26379]: connect -> ready +1ms
ioredis:connection send 1 commands in offline queue +0ms
ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,redis) +1ms
ioredis:redis write command[0] -> sentinel(sentinels,redis-staging) +61ms
ioredis:SentinelConnector adding sentinel <sentinel-internal-ip-1>:26379 +64ms
ioredis:SentinelConnector adding sentinel <sentinel-internal-ip-2>:26379 +0ms
ioredis:SentinelConnector sentinels +0ms [ { host: '<host>'26379 port: 26379 },
{ host: <sentinel-host-2>, port: 26379 },
{ host: <sentinel-host-3>, port: 26379 },
{ host: '<sentinel-internal-ip-1>', port: 26379 },
{ host: '<sentinel-internal-ip-2>', port: 26379 } ]
ioredis:redis status[<host>:26379]: ready -> close +77ms
ioredis:connection skip reconnecting since the connection is manually closed. +0ms
ioredis:redis status[<host>:26379]: close -> end +0ms
ioredis:connection error: Error: connect ETIMEDOUT +3s
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
  at Socket.<anonymous> (<path>/node_modules/ioredis/lib/redis.js:287:21)
  at Socket.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at Socket.emit (events.js:166:7)
  at Socket._onTimeout (net.js:332:8)
  at _runOnTimeout (timers.js:524:11)
  at _makeTimerTimeout (timers.js:515:3)
  at Timer.unrefTimeout (timers.js:584:5)`

But I am able to connect to the sentinels using medis, any idea what the problem could be?

**Comment by vhung92** [comment]
I've investigated further and the issue was not with `ioredis` but with our setup. ioredis is able to connect to one sentinel but when it is discovering other sentinels it used the internal IP's of the other sentinels to try and connect and since those were set up to be restricted `ioredis` was not able to connect to them, so my issue can be considered resolved
