### ISSUE TITLE
rfc - a preferred slave list in a sentinel setup

### ISSUE THREAD

**Issue by jedi4ever** [luin/ioredis#38]
We want to run a sentinel setup: 
- each webserver has it's own redis slave (will NOT become master - using `slave-priority = 0`)
- a set of sentinels running to protect us from partioning and handle the quorum
- a master and a few redis slaves for failover of master

In the current implementation , the slaves can be selected using the `role slave` but it picks a rather arbitrary slave. We would propose to have a way to indicate a list of preferred slaves for a client.

This is useful is in multi-AZ aws setups, where we want to keep the latency to app<->slave low .
A new syntax could look like: 

```
var redis = new Redis({
  sentinels: [{ host: 'localhost', port: 26379 }, { host: 'localhost', port: 26380 }],
  preferred_slaves: [ { prio: 10 , host: 'localhost', port: 6381 }]
  name: 'mymaster'
});
````

**Comment by luin** [comment]
Makes sense. Besides a list of preferred slaves, I think we may also accept a function to let user pick up the slave:

```javascript
var redis = new Redis({
  sentinels: [{ host: 'localhost', port: 26379 }, { host: 'localhost', port: 26380 }],
  preferredSlaves: function (availableSlaves) {
    return _.sample(availableSlaves);
  },
  name: 'mymaster'
});
```

**Comment by tangxinfa** [comment]
This feature is what i am looking for.

**Comment by doublesharp** [comment]
This is exactly the setup I need as well - any idea when it will be available?

**Comment by luin** [comment]
Aha, my fault. It seems that slave priority have to be set on the Redis side. See http://redis.io/topics/sentinel#slaves-priority for details.

**Comment by doublesharp** [comment]
I think there is a misunderstanding - the goal isn't to pick a Slave for failover but rather for reads. Assume there are 6 servers, all running Redis and Sentinel. 

- 1 Redis Master
- 2 Redis Replicas (a slave, but available for failover)
- 3 Redis Slaves (a slave, but not available for failover)

In the above setup with the 3 "Slaves" running on the application server reads can be made locally to the Slave instance while writes are made to the remote Master. It's assumed that the reads will not always be in sync with the writes based on the asynchronous Redis replication, but in cases where this is OK you get much better performance.

I actually updated the `ioredis` code/tests to handle this already, and was planning on submitting a pull request. 

It accepts either a function (as you suggested) with the available slaves provided as an argument or an array of objects with properties `ip`, `port`, and optionally `prio` (with a default of 1). I used `ip` rather than `host` to match the output from the `SENTINEL slaves` command. The first available "preferred" slave is returned, otherwise the default behavior of returning a random available slave is preserved. The `prio` isn't the actual slave priority, it is your preference priority - i want to connect to priority 1 because it is local, priority 2 because it is in my network segment, or worst case something else because 1 and 2 are not available. This would not affect failover or Sentinel functionality.

Let me know if you see any issues with the code below in `sentinel_connector.js` lines 150-204, with `var _this = this;` at the top of the function on line 136;

```javascript
// allow the options to prefer particular slave(s)
if (_this.options.preferredSlaves) {
  var preferredSlaves = _this.options.preferredSlaves;
  switch (typeof preferredSlaves) {
  case 'function':
    // use function from options to filter preferred slave
    selectedSlave = _this.options.preferredSlaves(availableSlaves);
    break;
  case 'object':
    if (!Array.isArray(preferredSlaves)) {
      preferredSlaves = [preferredSlaves];
    } else {
      // sort by priority
      preferredSlaves.sort(function (a, b) {
        // default the priority to 1
        if (!a.prio) {
          a.prio = 1;
        }
        if (!b.prio) {
          b.prio = 1;
        }

        // lowest priority first
        if (a.prio < b.prio) {
          return -1;
        }
        if (a.prio > b.prio) {
          return 1;
        }
        return 0;
      });
    }
    // loop over preferred slaves and return the first match
    for (var p = 0; p < preferredSlaves.length; p++) {
      for (var a = 0; a < availableSlaves.length; a++) {
        if (availableSlaves[a].ip === preferredSlaves[p].ip) {
          if (availableSlaves[a].port === preferredSlaves[p].port) {
            selectedSlave = availableSlaves[a];
            break;
          }
        }
      }
      if (selectedSlave) {
        break;
      }
    }
    // if none of the preferred slaves are available, a random available slave is returned
    break;
  }
}
if (!selectedSlave) {
  // get a random available slave
  selectedSlave = _.sample(availableSlaves);
}
```

**Comment by doublesharp** [comment]
Check out the commit in my fork here: https://github.com/doublesharp/ioredis/commit/8dfbe3287208e573056c61bbac191f8d9a855b33

**Comment by luin** [comment]
I got your point. The code looks great. Feel free to send a pull request and I'll definitely merge it.

**Comment by doublesharp** [comment]
@tangxinfa @jedi4ever this is now included in 2.4.0 :)

**Comment by tangxinfa** [comment]
If specify referredSlaves option as a function, it's better to pass in local address:

    SentinelConnector.prototype.resolveSlave = function (client, callback) {
      var _this = this;
      client.sentinel('slaves', this.options.name, function (err, result) {
        var localAddress = client.stream.localAddress;
        client.disconnect();
        if (err) {
          return callback(err);
        }
        var selectedSlave;
        if (Array.isArray(result)) {
          var availableSlaves = [];
          for (var i = 0; i < result.length; ++i) {
            var slave = utils.packObject(result[i]);
            if (slave.flags && !slave.flags.match(/(disconnected|s_down|o_down)/)) {
              availableSlaves.push(slave);
            }
          }
          // allow the options to prefer particular slave(s)
          if (_this.options.preferredSlaves) {
            var preferredSlaves = _this.options.preferredSlaves;
            switch (typeof preferredSlaves) {
            case 'function':
              // use function from options to filter preferred slave
              selectedSlave = _this.options.preferredSlaves(availableSlaves, localAddress);

Then we can computer ip distance and select the closed one, for example:

    function preferLocalSlave(slaves, localAddress) {
        var localIPSegments = new Array(4);
        if (net.isIPv4(localAddress)) {
            localIPSegments = localAddress.split('.');
        }

        var localSlaves = [];
        var remoteSlaves = [];

        for(var i = 0; i < slaves.length; ++i) {
            var slave = slaves[i];
            if (net.isIPv4(slave.ip)) {
                var slaveIpSegments = slave.ip.split('.');
                if (localIPSegments[0] === slaveIpSegments[0] &&
                    localIPSegments[1] === slaveIpSegments[1] &&
                    localIPSegments[2] === slaveIpSegments[2]) {
                    localSlaves.push(slave);
                    continue;
                }
            }

            remoteSlaves.push(slave);
        }

        return _.sample(localSlaves.length ? localSlaves : remoteSlaves);
    }

**Comment by tangxinfa** [comment]
There is a even more radicalness slave select algorithm i already implemented in production enveriment, with the flollow proirities:

1.  local slave
2.  local master
3.  remote slave
4.  remote master

This is because we deploy redis replica with 1 Master + 1 Slave, and in different data center to minimize replica throughput between data centers.

See gist https://gist.github.com/tangxinfa/1646be8aa7a6176a3eb731a914e54518 for more information.
