### ISSUE TITLE
utils.convertObjectToArray() pos increment not in if block

### ISSUE THREAD

**Issue by taichunmin** [luin/ioredis#467]
https://github.com/luin/ioredis/blob/master/lib/utils/index.js#L171

```js
exports.convertObjectToArray = function (obj) {
  var result = [];
  var pos = 0;
  for (var key in obj) {
    if (obj.hasOwnProperty(key)) {
      result[pos] = key;
      result[pos + 1] = obj[key];
    }
    pos += 2;
  }
  return result;
};
```

While I write a custom setArgumentTransformer, I found `pos += 2` not in `if (obj.hasOwnProperty(key))` block. Is it a bug?  Should I send a PR for that?

Maybe rewrite the convertObjectToArray as below:
```js
exports.convertObjectToArray = function (obj) {
  var result = [];
  for (var key in obj) {
    if (obj.hasOwnProperty(key)) {
      result.push(key, obj[key]);
    }
  }
  return result;
};
```

**Comment by luin** [comment]
Thank you for pointing this out! `pos += 2` should be put into the `hasOwnProperty` block. Using `[pos] = key` instead of `push` was originally for performance reasons. However, I agree that we should use `push` instead since that's the case why `push` is designed, and the performance difference between them can be neglected.

A PR is welcome!
