### ISSUE TITLE
Chaining custom commands in cluster mode

### ISSUE THREAD

**Issue by manast** [luin/ioredis#536]
According to the documentation "Chaining custom commands in the pipeline is not supported in Cluster mode.".
I am wondering, is this a limitation of ioredis or of redis itself? and do you have any information or link on why this limitation exists?

**Comment by manast** [comment]
@luin please, could you be so kind to share any insight you have in this issue?

**Comment by luin** [comment]
Sorry for the late response.

That's not a limitation of Redis. It's just not easy to support chaining custom commands in the cluster setup: ioredis always try `evalsha` first when sending custom commands, and when the command fails, `eval` will be sent instead. However, when it comes to pipelines, to make sure all commands in a pipeline will be received by Redis in order, ioredis sends `script exists` command to check if all lua scripts have loaded in the target redis node and will load the scripts which haven't loaded before sending the pipeline.

In the cluster setup, the nodes may change (e.g. failover happens) during the process of loading scripts, so it's hard to make sure that the scripts are loaded to the correct redis node. That's why this feature haven't been implemented.

**Comment by manast** [comment]
thanks for the throughout explanation.  When calling ```defineCommand```, why can't we just call ```SCRIPT LOAD``` and then after that we could just assume that the command is available?

**Comment by luin** [comment]
@manast Script cache may be cleared by the `SCRIPT FLUSH` command.  Despite that, calling `SCRIPT LOAD` when defining commands indeed solves the problem (we also need to resend all `SCRIPT LOAD` again when new connection has been made).

**Comment by manast** [comment]
Bump! :)

**Comment by btd** [comment]
Bump

**Comment by manast** [comment]
Bump!

**Comment by btd** [comment]
Bump

**Comment by manast** [comment]
Bump because it is an important issue!

**Comment by Rush** [comment]
Bump - interested in it as well.

**Comment by Gappa88** [comment]
interested

**Comment by firedfox** [comment]
Bump because we are using more Redis clusters in recent projects. This problem is getting more serious.

**Comment by ajwootto** [comment]
Also running into this.

**Comment by btzsoft** [comment]
we have the same issue.

**Comment by botzill** [comment]
Any updates on this issue? @luin 

Thx.

**Comment by jl9404** [comment]
> @manast Script cache may be cleared by the `SCRIPT FLUSH` command. Despite that, calling `SCRIPT LOAD` when defining commands indeed solves the problem (we also need to resend all `SCRIPT LOAD` again when a new connection has been made). Good idea!

wondering if we could always send `SCRIPT LOAD` to the pipeline so we can `EVALSHA` safely?

**Comment by RPallas92** [comment]
Same issue here

**Comment by andreimc** [comment]
same issue here

**Comment by kaikash** [comment]
same issue here

**Comment by artem-tolstykh** [comment]
Any updates on this issue? @luin

**Comment by NivLipetz** [comment]
Hi @luin , are there any plans for this issue to be fixed or is it a lost cause?
Thanks!

**Comment by shyimo** [comment]
Hi @luin , any plans about adding this ? 
we are now fully use Redis cluster and it's getting more serious now

**Comment by manast** [comment]
FYI, I just upgraded to 4.19.0 and some of Bull tests are failing. I need to investigate more, but for now I will need to lock ioredis to 4.18.0 in order to not break bull users environments.

**Comment by n0rick** [comment]
Hello, news?
ioredis has had several releases since 4.19.0
can we consider the problem solved?
