### ISSUE TITLE
HSET is replacing HMSET and behave in the same way redis 4.0

### ISSUE THREAD

**Issue by DrMegavolt** [luin/ioredis#551]
https://raw.githubusercontent.com/antirez/redis/4.0/00-RELEASENOTES
"HSET is now variadic, and HMSET is considered deprecated (but will be supported for years to come). Please use HSET in new code."

basically HSET can accept multiple key\values same as HMSET
HMSET myhash field1 "Hello" field2 "World" - OK
HSET myhash field1 "Hello" field2 "World" - Also OK starting from redis 4.0

Would it make sense to add same transformer as HMSET for HSET ? 
In my understanding it would not break backward compatibility.

**Comment by Mahmoud-Abd-Alhadi** [comment]
Any update on this? I have ioredis version "4.9.5" , and hset gives me "ReplyError: ERR wrong number of arguments for 'hset' command"

**Comment by sagar-artoon** [comment]
> Any update on this? I have ioredis version "4.9.5" , and hset gives me "ReplyError: ERR wrong number of arguments for 'hset' command"

@Mahmoud-Abd-Alhadi  If you have used hset command in NodeJS then I think you are calling it as **redisClient.hset("super_key", "sub_key1", undefined);** some of the variable is passed as undefined to hset command. It should have minimum 3 arguments or if there are more then 3 arguments then it should be have event numbers of arguments like given below : 
**redisClient.hset("super_key", "sub_key1", "sub_value1");** // 3 arguments
**redisClient.hset("super_key", "sub_key1", "sub_value1", "sub_key2", "sub_value2");** // 5 arguments

Otherwise there is another solution for it like given below : 
redisClient.hset(["test_key", "sub_key", undefined]);
There is no worry even if you pass any argument is passed as undefined. It will only give warning like : 
**node_redis: Deprecated: The HSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.**

redis npm version : 2.8.0
redis server version : 5.0.8
