### ISSUE TITLE
replace new Buffer() with Buffer.from()

### ISSUE THREAD

**Issue by idandagan1** [luin/ioredis#599]
Hi,
there is some buffer usage such as `new Buffer()`.
Using Buffer constructor is unsafe and is redundant.

According to Node.js docs: [ref](https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe)
> Developers should migrate all existing uses of the new Buffer() constructors to one of these new APIs.

I could create a PR and replace all `new Buffer()` with `Buffer.from()` (including examples and tests)

**Comment by luin** [comment]
Pull requests for this change are welcome! However, it seems that `Buffer.from()` is not supported until Node.js 6.x, which will be a breaking change if we replace `new Buffer()` with it since we provides support for Node.js 0.10.16. Can we check if the `Buffer.from()` exists, and if not, fallback to `new Buffer()`?

**Comment by ccs018** [comment]
Given that Node.js 0.10.16 is no longer a release supported by nodejs.org,
why continue to support it in the library?  0.10.x when end-of-life in
2016.  Sure, this would be a breaking change - uprev the major version and
call it a day.  Developers really should stay current with their
dependencies and that includes using a supported version of Node.js if not
the latest version.

https://github.com/nodejs/Release#release-schedule

Chris

**Comment by benjamingr** [comment]
@luin you can check if `Buffer.from` is available and if it is use it, otherwise `new Buffer` and `.fill`. 

@shaharmor since you're a maintainer here - you want to tackle this? (Feel free to say no and I'll PR)

**Comment by benjamingr** [comment]
Also, I don't think you should support Node.js 0.10.16 since we (Node) no longer support it.

In fact, 0.10.x, 0.12.x, 1.x, 2.x, 3.x, 5.x, 7.x are all EoL, 4.x becomes EoL in ~ a month. 

To clarify, if you _don't_ change this then every updated node install will emit a process warning every time ioredis is used (but no code will break)
