### ISSUE TITLE
Does ioredis handle connections?

### ISSUE THREAD

**Issue by sulthan-ahmed** [luin/ioredis#750]
Hi, I have a nodejs app that connects to redis via ioredis at various different times (e.g. save, read, delete etc).  I'm not sure what is the best practice for connections.

1. Should I create a connection at the beginning of starting the app.  Reuse that redis instance whenever I need to?
2. Create and close a redis connection every time I use it?
3. It doesn't matter ioredis will detect open connections and use any available?

Apologies if someone has already asked that question, I couldn't find it anywhere

**Comment by zhongshixi** [comment]
1. I think you should always use a single redis instance to communicate with redis if your nodejs is a single instance.
2. you should always use the existing connection ( like connection pool for database), since creating and closing connection will add overhead
3. that is a good question, unfortunately I do not have knowledge to answer it now, probably someone will answer it for you

**Comment by sulthan-ahmed** [comment]
thanks @zhongshixi 👍 

I'll wait for someone to answer question 3 before closing this issue

**Comment by sulthan-ahmed** [comment]
Thanks @vflopes
