### ISSUE TITLE
Offline queue size limit

### ISSUE THREAD

**Issue by dg3feiko** [luin/ioredis#76]
As ioredis supports offline queue, is it possible that the queue will grow to infinity if the client can not connect to redis server for long time, which will lead to huge memory growth ?

If so, I think it is nice to have a param to control the max size of the offline queue, and eviction policy, e.g. LRU

**Comment by luin** [comment]
How does LRU work when used as the eviction policy of the offline queue?

**Comment by dg3feiko** [comment]
I didnt drill down much into the detail, but i think the command currently queued into the buffer remains a pending state until is it handled by redis server, so that there is no callback fired in the middle( i am not sure this behaviour and correct me if i am wrong). One a command or a batch of command is going to be dropped, just fire a callback with failure.

**Comment by dg3feiko** [comment]
A lru buffer, may it be a Ring Buffer more accurately, holds the last N command that issued but not processed, once the buffer is full, the oldest serveral will be dropped

**Comment by dg3feiko** [comment]
Actually LRU may not be the best policy for cases, but anyway there should be a way to control the growth

**Comment by luin** [comment]
Seems a fixed-size offline queue can solve the problem.

**Comment by dg3feiko** [comment]
If it is full, then any incoming command will be failed immediately?

**Comment by luin** [comment]
Accurately a fixed-size FIFO queue. The oldest command would be flushed with an error when the queue gets above a certain size.

**Comment by AVVS** [comment]
This is related to #61, even though solves the problem differently. fixed FIFO queue is nice when you have outage and then spike of requests come in and they are flushed with an error, but only if none of them mutate state. 

If you have some that mutate state (lets say we manage sessions in redis) - it may actually do plenty of harm, so gotta be somewhat careful with this

**Comment by dirkbonhomme** [comment]
Is the queue size maybe something that can be included in the retry strategy? Or is it best to keep this separated?

```
retryStrategy: function (times, commandsQueue) {
    if(times > 10 && commandsQueue.length > 500){
        commandsQueue.splice(...)
   }
   ...
}
```

**Comment by luin** [comment]
@dirkbonhomme I really like this approach, which let developer deal with offline queue in a more flexible way.
Currently offline queue could be accessed by:

```javascript
retryStrategy: function (times) {
    if(times > 10 && redis.offlineQueue.length > 500){
        redis.offlineQueue.pop(...)
   }
}
```
However `offlineQueue` property is not documented and it's a [double ended queue](https://github.com/petkaantonov/deque) instead of a typical array.

**Comment by shaharmor** [comment]
I think this is a critical feature as i have already witnessed multiple times a server going down because the queue was filling up.

I think that having a property to limit the # of items in the queue should be sufficient.

**Comment by BridgeAR** [comment]
I thought about this issue before too and I have the same concerns as @AVVS that the flushed commands might do more harm than help.
And even if the commands would not mutate state, they still might be harmful, as the result might be expected before handling something else.

And the number of commands is really not a good indicator for memory growth. There might be a few commands that use up more memory than a whole lot of small ones.

The suggestion from @dirkbonhomme is likely the only "safe" way to handle this. The user is able to check all commands, if they exceed a specific memory amount, no matter if it's done by checking each command arg or by checking the number of commands (maybe all commands are of a fixed size). He's also able to distinguish between commands that might be harmful to throw away and between others and so forth.

As this feature is not yet released I suggest to remove it again and to update the docs instead to outline how to handle such situations.

**Comment by luin** [comment]
Yes, I like the suggestion from @dirkbonhomme, and since `offlineQueue` property is not a native array (as my previous comment said), we should document it.
However, although this way is very flexible, it may not that straightforward to use.
I don't think flushing commands that mutate state do harm since if your application relies on a command's executing successfully, you'd better handle it's error response properly. For a command that relying on the previous command, they would be better to be sent within a transaction.

**Comment by BridgeAR** [comment]
You are right that the user should handle the error. But if you shift a value from the commands queue that alters state and other commands were already added to the command queue that rely on that altered state (this is very likely as the user would not get any error so far) it is fairly difficult to handle this properly without just flushing the whole queue and starting all over again.

And the amount of commands is still not really useful. Instead I recommend to add a `maxOfflineQueueMemorySize` option and to collect the overall memory footprint of the offline queue (using `Buffer.byteLength()` should be a god enough way to measure this).

**Comment by luin** [comment]
The commands that are shifted from the command queue will be rejected by a specified error ("offline queue is full"). Say we have two commands that the latter command relies on the former one.:

```javascript
redis.set('foo', 'bar').then(function (res) {
  return redis.get('foo');
});
```

The second command will only be invoked when the first command is successful, so that shift the first command from the offline queue when the offline queue is full should not break the application.

I agree with you that `maxOfflineQueueMemorySize` may be better than `maxOfflineQueueSize`. However it's difficult to get the size of commands because we only converted them to redis protocol strings at the time of sending them to the redis server instead of pushing them to the offline queue.

I think we may support `maxOfflineQueueSize` and at the same time document the solution from @dirkbonhomme.

**Comment by dirkbonhomme** [comment]
I think there's just no way a library like this can decide on its own what to do with a commands queue in case of a disconnect. Some projects won't care (e.g. when storing non-critical logs into Redis), some projects will want 100% guarantees (e.g. when pushing critical data) and some projects will probably dump all queued commands into a file and do a controlled crash.

My suggestion is to document some examples on how to use the retryStrategy/offlineQueue. Users can then either copy-paste these examples or adjust them to their liking.

**Comment by luin** [comment]
Let user handle offline queue in retryStrategy is a very flexible way, however I'm afraid that's not enough since retryStrategy is only invoked when reconnecting, user can't do anything with offline queue between retries. `maxOfflineQueueSize` is useful for this case.
Flushing the overflow commands is a simple way and shouldn't cause any problem about the state if developers handle the errors of each command properly.
What's more, we may emit an 'offlineQueueOverflow' event when the offline line queue size reaches the `maxOfflineQueueSize` option to let users handle the offline queue themselves before we flushing the overflow commands.

Related issue: https://github.com/NodeRedis/node_redis/issues/932.

**Comment by luin** [comment]
I reverted the `maxOfflineQueueSize` from the master branch and open a pull request (https://github.com/luin/ioredis/pull/241) instead so we can discuss it.
