### ISSUE TITLE
nodejs.RangeError: Maximum call stack size exceeded when use hmset 

### ISSUE THREAD

**Issue by yuu2lee4** [luin/ioredis#801]
when hmset get too much args(i passed 163368 args),it will report `nodejs.RangeError: Maximum call stack size exceeded`

**Comment by FanAs** [comment]
Why is it closed? It's a major problem in a "robust, performance-focused" library because we use it in our production solution where count of arguments can be about 200K. It isn't the best solution to transfer them as multiple arguments because stack will be exceeded very soon.

**Comment by tuananh** [comment]
divide them into chunks and do it in one pipeline maybe?

**Comment by luin** [comment]
Really sorry for the late response. I am wondering how to reproduce the exception. Here's the code I used for test:

```javascript
const Redis = require('ioredis')
const redis = new Redis()

const fields = []
const obj = {}
for (let i = 0; i < 400000; i++) {
  const key = (Math.random() * 100000 | 0) + 'keykeykeykeykeykeykeykeykeykeykey'
  const value = 'valuevaluevaluevaluevaluevaluevaluevaluevaluevaluevalue'
  fields.push(key)
  fields.push(value)
  obj[key] = value
}

async function test () {
  console.log(await redis.hmset('key', fields))
  console.log(await redis.hmset('key', obj))
}

test()
```

And the output is:

```
ioredis git:master ❯ node test
OK
OK
```

**Comment by FanAs** [comment]
@luin Hello, thank you. As be able to use ioredis, I found that limit on my machine is 125100 keys - if there is more then that, it fails.
But it depends on the stack size, I guess mine is default.
But you can try 1 million - for ex.
```javascript
const keys = [];
for (let i = 0; i < 1000000; i++) keys.push(i.toString());
const value = await redis.get(keys);
```

**Comment by FanAs** [comment]
@tuananh it's a half-solution - I need to know how big my stack size is, solve it in set, get, hmset, hmget ... functions - not the best way to make things work.
@luin It would be ideal and more faster if there will be option in client that disables array flatting and takes an array in arguments instead of spreading all arguments to array.

**Comment by tuananh** [comment]
@FanAs easy way would be increase the stack size buy using `--stack-size=` flag?

**Comment by tuananh** [comment]
if i change the above test script to 1,000,000, i got `ERR Protocol error: invalid multibulk length`

looks like it's a limit in redis? https://github.com/antirez/redis/blob/6c60526db91e23fb2d666fc52facc9a11780a2a3/src/networking.c#L1024

**Comment by ethanresnick** [comment]
I ran into this too, and I think it's mostly a documentation issue that ioredis really should address.

Essentially, the ioredis APIs for `hmset`, `hmget`, and possibly others are documented as though the arguments to the command must be passed as arguments one by one. I.e., if you want to set 100,000 hash keys, the docs suggest you'd call `commander.hmset` with 200,001 arguments (200,000 for the hash keys and their values, plus one for the redis key holding the hash). But, as noted in the OP, trying to call a method with so many arguments causes v8 to crash, because each argument gets allocated as a variable in the function's stack frame. 

The simplest workaround is actually to call `commander.hmset("keyHoldingHash", my200_000ItemArray)`. This works because the `Command` class [flattens](https://github.com/luin/ioredis/blob/0db527fd4266913583bce55245940e825dba1a46/lib/command.ts#L180) it's arguments — which is great, but that's the part that's totally undocumented and that it's unclear whether callers can safely rely on. So, if that flattening is here to stay, it should be documented, probably with a note that it can be used with any command to work around this limit on the number of arguments allowed to a function call.

**Comment by FanAs** [comment]
Please, it's still the biggest problem in ioredis - array flattening, copying and spreading are evil when you are making fast library.
Is there any way to solve it without dirty hacks? Possible config that disable it?

**Comment by FanAs** [comment]
Any updates on this?

**Comment by mster** [comment]
Still encountering this issue.

**Comment by Saarett** [comment]
Still encountering it to this day ✋

**Comment by argahsuknesib** [comment]
Same, still encountering this issue.

**Comment by shardul-cometchat** [comment]
Tried the method @ethanresnick suggested, with `hdel` for `1,97,000` keys but it fails with the error `ERR Protocol error: invalid multibulk length` as mentioned earlier by @tuananh . I feel all the commands which accept multiple fields should have a limit mentioned in docs.

**Comment by akeating** [comment]
Was bitten by this using `hdel`. The lib supports passing a array, but the typescript definition does not appear to be accurate. There is some [evidence](https://github.com/redis/ioredis/blob/2f9843ddfa8d46cbee6c858fefbf9c2cd3852503/examples/hash.js#L25) that use of an array is supported. In this hash example, both usages are detailed.
