### ISSUE TITLE
Pipeline requests failing in cluster mode after bundling with Parcel

### ISSUE THREAD

**Issue by jbfru45** [luin/ioredis#827]
Parcel production builds use name-mangling on node_modules to reduce the bundle size. This is causing Redis cluster pipeline requests to throw exceptions due to line 15 in pipeline.ts:

`this.isCluster = this.redis.constructor.name === 'Cluster'`

The Cluster class is renamed, so this check always returns false. I realize this isn't really a bug in ioredis, but it would be nice to be able to bundle ioredis with name mangling enabled.

**Comment by kroleg** [comment]
1. In `Pipeline` `this.redis` is actually a `Redis.prototype`
2. It's not possible to import `Cluster` into `pipeline.ts` because it would create circular dependency, so we can't use `isPrototypeOf` (instead of constructor.name check).

Other possible way to "detect" `Cluster` is to check presense of method which exists in `Cluster`, but doesn't exist in `Redis`, for example `.nodes()`. I.e. need to change `this.isCluster = this.redis.constructor.name === 'Cluster'` to `this.isCluster = !!this.redis.nodes`

**Comment by JeffreyCA** [comment]
I ran into this issue with Webpack + Terser, where I got errors saying some methods were 'undefined'.

One workaround is to disable function name mangling. by setting `keep_fnames` to `true`.

**Comment by marcbachmann** [comment]
This should have been fixed with https://github.com/luin/ioredis/commit/bfc194dcad2af527e802d6f5b060f0b0779e840d in v4.23.1
