### ISSUE TITLE
Destructive behavior for .keys() method

### ISSUE THREAD

**Issue by Somebi** [luin/ioredis#847]
> Every command will be sent to exactly one node. For commands containing keys, (e.g. GET, SET and HGETALL), ioredis sends them to the node that serving the keys, and for other commands not containing keys, (e.g. INFO, KEYS and FLUSHDB), ioredis sends them to a random node.

Why you decided to send keys to only a single node? Took me a while to figure out why cookies jar stopped working as intended, after moving to redis cluster.

If there would be a need to get specific node sharded keys, then there should be a method like `nodeKeys(node, path)`

This is destructive behavior, because it can break multiple modules, which were using `.keys()` method with intention to get **all** keys, not only sharded keys.

**Comment by luin** [comment]
Thank you for pointing this out!

I've to say this behavior is a tradeoff among many factors. One of the most vital point is Redis cluster is not designed as a drop in replacement of standalone Redis (contrasting with Codis), thus the users should change their code more or less to switch to Redis cluster. For example, `KEYS *` may return wrong results during failover or network failure given Redis cluster is an AP-system (let alone it is not recommended to use `KEYS` command since Redis clusters typically have large sets of keys).

It's possible (yet hard) that people could build a logic layer on top of ioredis cluster to overcome the issues, but it will definitely require a lot of efforts which beyonds the scope of this module.
