### ISSUE TITLE
Prototype pollution attack

### ISSUE THREAD

**Issue by mostafa** [luin/ioredis#877]
* **Version**: 2.8.0
* **Platform**: Node v12.3.0
* **Description**: Proof of concept: https://github.com/mostafa/js-pp-poc

**Comment by luin** [comment]
Thank you for pointing this out! The behavior is caused by converting arguments to strings needs to invoke `#toString()` on each argument.

For now, however, I couldn't think of any way a hacker can take advantage of this behavior without having the write permission to the code (simply `JSON.parse()` won't get an object with a function value property, so it's impossible for hackers to construct malicious strings as input for your application that can be parsed into objects with `toString()` property).

Did I miss anything?

**Comment by mostafa** [comment]
But you can still keep them away by just disabling any overridden function from the `__proto__`.

**Comment by luin** [comment]
@mostafa I got your point. However, there are many ways to achieve this behavior without `__proto__`. For example:

```javascript
class A {
  toString() {
    return 'hi'
  }
}
```

And both `__proto__` and the usage above are pretty normal that we've been used for years and they shouldn't be forbidden.

Since `#toString()` will be invoked every time when `String()` is called, and `String()`, developers take responsibility for their code. They shouldn't delete files in `#toString()`, just like they shouldn't delete files in any other places.

Given that, I'm closing this issue for now. Anyway, Thanks for reporting this. We take security issues very serious, so feel free to let me know if there are other issues.
