### ISSUE TITLE
Cluster UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jstewmon** [luin/ioredis#883]
I'm intentionally causing a connection error (by omitting a NAT mapping for one cluster node) to verify my application's error handling, but I'm seeing an UnhandledPromiseRejectionWarning:

```
(node:18) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:288:20)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at TCP.<anonymous> (net.js:586:12)
```

My code is executing a multi command like this:
```js
redisClient
      .multi()
      .expire(key, this.expire)
      .hgetall(key)
      .exec()
      .then(
        async ([[expErr, expVal], [hashErr, hashVal]]) => {
          if (expErr || hashErr) {
            throw expErr || hashErr;
          }
          return Object.values(hashVal);
        },
      )
      .then(x => cb(null, x))
      .catch(err => cb(err, []));
```

I believe this is the relevant debug output preceding the throw:
```
  ioredis:redis status[127.0.0.1:7000]: [empty] -> wait +5ms
  ioredis:delayqueue send 1 commands in failover queue +119ms
  ioredis:redis status[127.0.0.1:7000]: wait -> connecting +1ms
  ioredis:redis queue command[127.0.0.1:7000]: 0 -> multi([]) +1ms
  ioredis:redis queue command[127.0.0.1:7000]: 0 -> expire([ 'mykey', '2592000' ]) +0ms
  ioredis:redis queue command[127.0.0.1:7000]: 0 -> hgetall([ 'mykey' ]) +0ms
  ioredis:redis queue command[127.0.0.1:7000]: 0 -> exec([]) +1ms
  ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:7000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7000
} +9ms
  ioredis:redis status[127.0.0.1:7000]: connecting -> close +2ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +1ms
  ioredis:redis status[127.0.0.1:7000]: close -> end +0ms
```

The promise for `exec` does reject as expected (json taken from my log):
```json
{
  "type": "Error",
  "message": "Connection is closed.",
  "stack": "Error: Connection is closed.\n    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)\n    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)\n    at Object.onceWrapper (events.js:288:20)\n    at Socket.emit (events.js:200:13)\n    at Socket.EventEmitter.emit (domain.js:471:20)\n    at TCP.<anonymous> (net.js:586:12)",
  "previousErrors": [
    {
      "previousErrors": "[Circular]"
    },
    {
      "previousErrors": "[Circular]"
    },
    {
      "previousErrors": "[Circular]"
    }
  ]
}
```

Is there something I can do to catch the rejection?

Possibly related, the `'error'` event listener I have attached to the cluster does not trigger when this happens, which also seems unexpected.

I was using `4.9.0` and tried updating to `4.9.5`, and have the same experience with both versions.

TIA for any guidance!

**Comment by luin** [comment]
You can see the command that caused the UnhandledPromiseRejectionWarning by enabling `showFriendlyErrorStack` option: 

```javascript
new Cluster([], { showFriendlyErrorStack: true })
```

It's also possible that the command were sent from ioredis internal, if that is the case, we'll figure out a way to solve it.

**Comment by jstewmon** [comment]
@luin thanks for the reply.

The `showFriendlyErrorStack` option isn't working when passed to the `Cluster` constructor because [`this.options`](https://github.com/luin/ioredis/blob/master/lib/cluster/index.ts#L70) is somehow having `{showFriendlyErrorStack: false}`, so `lodash.defaults` does not pick up the value passed to the constructor.

I couldn't figure out why that's happening, but it seems like `merge({}, this.options, DEFAULT_CLUSTER_OPTIONS, options)` would be more appropriate to ensure the passed options override the defaults.


Anyway, I worked around that using the chrome inspector and I see the friendly stack trace reporting the callsite of the `exec` call in my original post.

This code is running during an http request, and I've confirmed that the callsite is only executed once during a request. Yet, I count 16 of these unhandled rejections for every request. If I pause on uncaught exceptions with inspector, it pauses 17 times on [`throw execResult[0]`](https://github.com/luin/ioredis/blob/master/lib/transaction.ts#L47).

Are those numbers a clue as to what might be happening?

**Comment by jstewmon** [comment]
I put together a minimal reproduction:

docker-compose.yaml:
```yaml
version: '3.7'
services:
  web:
    image: node:dubnium-alpine
    user: node
    working_dir: /home/node/app
    depends_on:
      - redis
    environment:
      DEBUG: 'ioredis:*'
      NODE_ENV: dev
    ports:
      - '3000:3000'
      - '9222:9222'
    volumes:
      - .:/home/node/app
    init: true
    command: node --inspect=0.0.0.0:9222 index.js
    stdin_open: true
  redis:
    image: grokzen/redis-cluster:5.0.4
    environment:
      IP: '0.0.0.0'
    ports:
      - '7000-7005:7000-7005'

```

package.json:
```json
{
  "name": "ioredis-repo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ioredis": "^4.9.5"
  }
}
```

index.js:
```js
const http = require('http');
const Redis = require('ioredis');
const util = require('util');
const cluster = new Redis.Cluster(
  [{host: 'redis', port: 7000}],
  {
    natMap: {
      '127.0.0.1:7000': {host: 'redis', port: 7000},
      '127.0.0.1:7001': {host: 'redis', port: 7001},
      // '127.0.0.1:7002': {host: 'redis', port: 7002},
      '127.0.0.1:7003': {host: 'redis', port: 7003},
      '127.0.0.1:7004': {host: 'redis', port: 7004},
      '127.0.0.1:7005': {host: 'redis', port: 7005},
    },
  },
).on('error', err => {
  console.error('CLUSTER ERROR:', err)
});

http.createServer(async (req, res) => {
  const key = 'foo';
  cluster
    .multi()
    .expire(key, 300)
    .hgetall(key)
    .exec()
    .then(results => res.end(JSON.stringify(results)))
    .catch(err => {
      res.statusCode = 500
      res.end(util.format('%o', err))
    });
}).listen(3000);
```

http request:
```
$ curl -i http://localhost:3000/
HTTP/1.1 500 Internal Server Error
Date: Fri, 07 Jun 2019 18:05:53 GMT
Connection: keep-alive
Content-Length: 811

{ Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
  [stack]:
   'Error: Connection is closed.\n    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)\n    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at TCP._handle.close (net.js:606:12)',
  [message]: 'Connection is closed.',
  previousErrors: [ [Circular], [Circular], [Circular], [length]: 3 ] }
```

snippet from container output:
```
2019-06-07T18:05:53.703Z ioredis:cluster:connectionPool Connecting to 127.0.0.1:7002 as master
2019-06-07T18:05:53.704Z ioredis:redis status[127.0.0.1:7002]: [empty] -> wait
2019-06-07T18:05:53.704Z ioredis:delayqueue send 1 commands in failover queue
2019-06-07T18:05:53.704Z ioredis:redis status[127.0.0.1:7002]: wait -> connecting
2019-06-07T18:05:53.704Z ioredis:redis queue command[127.0.0.1:7002]: 0 -> multi([])
2019-06-07T18:05:53.705Z ioredis:redis queue command[127.0.0.1:7002]: 0 -> expire([ 'foo', '300' ])
2019-06-07T18:05:53.705Z ioredis:redis queue command[127.0.0.1:7002]: 0 -> hgetall([ 'foo' ])
2019-06-07T18:05:53.705Z ioredis:redis queue command[127.0.0.1:7002]: 0 -> exec([])
2019-06-07T18:05:53.706Z ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:7002
2019-06-07T18:05:53.706Z ioredis:redis status[127.0.0.1:7002]: connecting -> close
2019-06-07T18:05:53.706Z ioredis:connection skip reconnecting because `retryStrategy` is not a function
2019-06-07T18:05:53.706Z ioredis:redis status[127.0.0.1:7002]: close -> end
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:6) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (/home/node/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
```

**Comment by jstewmon** [comment]
The number of unhandled rejections corresponds to the `maxRedirections` option. If I set it to `0`, I get `0` unhandled rejections.

**Comment by jstewmon** [comment]
The unhandled rejections are originating [here](https://github.com/luin/ioredis/blob/master/lib/pipeline.ts#L126). If I change it to `_this.exec().catch(err => console.error('BOOM %o', err))`, I get the errors logged instead of unhandled rejection warnings.

**Comment by luin** [comment]
Thanks for providing the minimal reproduction, it've been a great help. I created a pr to solve the issue: https://github.com/luin/ioredis/pull/884. Still writing tests for it.

**Comment by kunal-til** [comment]
Hi,

I am facing the same issue in ioredis@4.9.0, but I have redis sentinel rather than redis cluster on production. So will upgrading to ioredis to 4.10.2 will solved for me also?

**Comment by luin** [comment]
@kunal-til It should only happens when `exec()` is called multiple times, which is often the case in cluster mode since pipeline in cluster mode will retry when failed in some cases. Did you code call `exec()` multiple times? Is there a minimal reproduction?

**Comment by kunal-til** [comment]
@luin We are not using the pipeline in code.

**Comment by luin** [comment]
@kunal-til Then that should be a separate problem. Please create a new issue for that.

**Comment by kunal-til** [comment]
@luin Thanks for the quick response.

**Comment by abhijeetbadouriya** [comment]
This is error we are getting 

0|main  | 2019-06-28 17:24:10 +05:30: clientRead: {"options":{"sentinels":[{"host":"10.10.94.161","port":26379},{"host":"10.10.90.135","port":26379},{"host":"10.10.159.6","port":26379}],"name":"mymaster","role":"slave","connect_timeout":3600000,"port":6379,"host":"localhost","family":4,"connectTimeout":10000,"keepAlive":0,"noDelay":true,"connectionName":null,"natMap":null,"enableTLSForSentinelMode":false,"updateSentinels":true,"password":null,"db":0,"dropBufferSupport":false,"enableOfflineQueue":true,"enableReadyCheck":true,"autoResubscribe":true,"autoResendUnfulfilledCommands":true,"lazyConnect":false,"keyPrefix":"","reconnectOnError":null,"readOnly":false,"stringNumbers":false,"maxRetriesPerRequest":20,"maxLoadingRetryTime":10000,"showFriendlyErrorStack":false},"_events":{},"_eventsCount":4,"scriptsSet":{},"commandQueue":{"_head":0,"_tail":0,"_capacityMask":3,"_list":[null,null,null,null]},"offlineQueue":{"_head":0,"_tail":0,"_capacityMask":3,"_list":[null,null,null,null]},"connector":{"connecting":true,"options":{"sentinels":[{"host":"10.10.94.161","port":26379},{"host":"10.10.90.135","port":26379},{"host":"10.10.159.6","port":26379}],"name":"mymaster","role":"slave","connect_timeout":3600000,"port":6379,"host":"localhost","family":4,"connectTimeout":10000,"keepAlive":0,"noDelay":true,"connectionName":null,"natMap":null,"enableTLSForSentinelMode":false,"updateSentinels":true,"password":null,"db":0,"dropBufferSupport":false,"enableOfflineQueue":true,"enableReadyCheck":true,"autoResubscribe":true,"autoResendUnfulfilledCommands":true,"lazyConnect":false,"keyPrefix":"","reconnectOnError":null,"readOnly":false,"stringNumbers":false,"maxRetriesPerRequest":20,"maxLoadingRetryTime":10000,"showFriendlyErrorStack":false},"sentinelIterator":{"sentinels":[{"host":"10.10.94.161","port":26379},{"host":"10.10.90.135","port":26379},{"host":"10.10.159.6","port":26379}],"cursor":0},"retryAttempts":0,"stream":{"connecting":true,"_hadError":false,"_handle":{"reading":false,"onconnection":null},"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":true,"emitClose":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":false,"domain":null,"_events":{"connect":[null,null]},"_eventsCount":5,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null,"timeout":10000}},"retryAttempts":0,"status":"connecting","condition":{"select":0,"auth":null,"subscriber":false},"stream":{"connecting":true,"_hadError":false,"_handle":{"reading":false,"onconnection":null},"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":true,"emitClose":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":false,"domain":null,"_events":{"connect":[null,null]},"_eventsCount":5,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null,"timeout":10000}}
0|main  | 2019-06-28 17:24:10 +05:30: 2019-06-28T11:54:10.208Z ioredis:redis queue command[localhost:6379]: 0 -> hget([ 'match_schedule_2', 'match_schedule_2_diner' ])


0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.768Z ioredis:connection error: Error: connect ETIMEDOUT
0|main  | 2019-06-28 17:24:13 +05:30: Error Error: connect ETIMEDOUT
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.768Z ioredis:redis status[localhost:6379]: connecting -> close
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.769Z ioredis:connection reconnect in 50ms
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.769Z ioredis:redis status[localhost:6379]: close -> reconnecting
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.769Z ioredis:connection error: Error: connect ETIMEDOUT
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.770Z ioredis:redis status[localhost:6379]: connecting -> close
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.770Z ioredis:connection skip reconnecting since the connection is manually closed.
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.770Z ioredis:redis status[localhost:6379]: close -> end
0|main  | 2019-06-28 17:24:13 +05:30: errror:      Error: Connection is closed.
0|main  |     at close (/nodeApi/node_modules/ioredis/built/redis/event_handler.js:109:25)
0|main  |     at Socket.<anonymous> (/nodeApi/node_modules/ioredis/built/redis/event_handler.js:76:20)
0|main  |     at Object.onceWrapper (events.js:277:13)
0|main  |     at Socket.emit (events.js:189:13)
0|main  |     at Socket.EventEmitter.emit (domain.js:441:20)
0|main  |     at TCP._handle.close (net.js:600:12)
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.780Z ioredis:connection error: Error: connect ETIMEDOUT
0|main  | 2019-06-28 17:24:13 +05:30: Error Error: connect ETIMEDOUT
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.784Z ioredis:redis status[localhost:6379]: connecting -> close
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.784Z ioredis:connection reconnect in 50ms
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.785Z ioredis:redis status[localhost:6379]: close -> reconnecting
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.805Z ioredis:connection error: Error: connect ETIMEDOUT
0|main  | 2019-06-28 17:24:13 +05:30: [ioredis] Unhandled error event: Error: connect ETIMEDOUT
0|main  |     at Socket.<anonymous> (/nodeApi/node_modules/ioredis/built/redis/index.js:270:31)
0|main  |     at Object.onceWrapper (events.js:277:13)
0|main  |     at Socket.emit (events.js:189:13)
0|main  |     at Socket.EventEmitter.emit (domain.js:441:20)
0|main  |     at Socket._onTimeout (net.js:443:8)
0|main  |     at ontimeout (timers.js:436:11)
0|main  |     at tryOnTimeout (timers.js:300:5)
0|main  |     at listOnTimeout (timers.js:263:5)
0|main  |     at Timer.processTimers (timers.js:223:10)
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.806Z ioredis:redis status[localhost:6379]: connecting -> close
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28T11:54:13.806Z ioredis:connection reconnect in 50ms
0|main  | 2019-06-28 17:24:13 +05:30: 2019-06-28
