### ISSUE TITLE
Cannot connect after quit command

### ISSUE THREAD

**Issue by manast** [luin/ioredis#928]
Trying to connect after calling quit results in the following exception:

```
Error: Connection is closed.
    at Redis.connectionCloseHandler (/Users/manuelastudillo/Dev/taskforce/bull/node_modules/ioredis/built/redis/index.js:295:24)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Redis.emit (events.js:211:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

How to reproduce:
```
async function test() {
  const IORedis = require('ioredis');

  const client = new IORedis();

  client.on('end', async () => {
    console.log('end');
    try {
      await client.connect();
    } catch (err) {
      console.error(err);
    }
  });

  client.on('error', async err => {
    console.error(err);
  });

  await client.quit();
}

test();
```

From what I can understand from the code it seems that the status property is not properly updated in the case of quit (or disconnect btw).

**Comment by luin** [comment]
Thank you for pointing this out. This is a bug happening when connecting immediately after "end", thus changing:

```javascript
    try {
      await client.connect();
    } catch (err) {
      console.error(err);
    }
```

to

```javascript
    setTimeout(() => {
      client.connect();
    }, 0)
```

Will avoid the reconnecting and will be able to connect successfully.

This issue is caused by the handlers for the events emitted from the previous connection being executed during the next connection being made.

I created a pull request to fix this issue by introducing a connection epoch to distinguish different connections.
