### ISSUE TITLE
Is there way to close MONITOR connection?

### ISSUE THREAD

**Issue by PrashanthShetty** [luin/ioredis#956]
Hello,
I am trying to close MONITOR connection by calling redis.disconnect(); but looks like its not working. I know MONITOR opens a new connection. Is there a way to disconnect MONITOR connection? Am I missing something here.

**Comment by knoxcard** [comment]
```
redis.monitor(function(err, monitor) {
  monitor.on("monitor", function(time, args, source, database) {});
});
```

**Comment by luin** [comment]
@knoxcard The documentation seems to be a little misleading. Actually, the `monitor` command does create a new connection (and no other commands are valid on **this** connection). The value that returned by `monitor` command is a `Redis` instance, so you can close it via `#disconnect()` command:

```javascript
async () => {
  const monitor = await redis.monitor()
  monitor.on('monitor', console.log)
  // Any other tasks
  monitor.disconnect()
}
```

**Comment by knoxcard** [comment]
I knew it!  I was actually going write the code out just like that because it makes total sense to me `monitor.disconnect()`, but I couldn't find it in the documentation.  Then I tried a Google search and didn't find it.  Just did another Google search and modified the query and now I see it yields two results...

https://www.google.com/search?rlz=1C1CHBF_enUS715US715&ei=geRvXfHbOt6y0PEPoqGZoAU&q=%22monitor.disconnect%28%29%22+%22ioredis%22&oq=%22monitor.disconnect%28%29%22+%22ioredis%22&gs_l=psy-ab.3..33i160.2510.4652..4874...0.0..0.118.196.1j1......0....1..gws-wiz.K3kRMZl84KE&ved=0ahUKEwixoIDEybfkAhVeGTQIHaJQBlQQ4dUDCAs&uact=5

Thanks @luin!

**Comment by PrashanthShetty** [comment]
Thank you @knoxcard and @luin . I think issue is with TS definition shows redis.monitor() method is void. 
This is what I see in TS definition for redis.monitor().

        monitor(callback: (err: Error, res: NodeJS.EventEmitter) => void): void;
        monitor(): Promise<NodeJS.EventEmitter>;

That's why VS code IntelliSense is not showing the return type as redis instance and also check the callback parameter, it is NodeJS.EventEmitter.

**Comment by knoxcard** [comment]
I use Sublime, so I am not sure what needs to be done there.  Is that something you know how to fix?

**Comment by PrashanthShetty** [comment]
I think updating the npm package with right TS definition should solve this. 

https://www.npmjs.com/package/@types/ioredis

I am using above npm package for TS definition.

**Comment by PrashanthShetty** [comment]
I modified TS file locally and that works for me.

 monitor(callback: (err: Error, res: Redis) => void): Promise<Redis>;
 monitor(): Promise<Redis>;

**Comment by christopher-caldwell** [comment]
The types are still showing as `EventEmitter`
