### ISSUE TITLE
Better typescript support

### ISSUE THREAD

**Issue by gengjiawen** [luin/ioredis#963]
Since this repo has been rewritten by ts, let's publish the types to npm too. So user wouldn't need download types dependency.

This is also the recommend way for ts libs.

**Comment by luin** [comment]
Yes, I'd like to publish the type definition. However, there're many works to be done before we publishing the definition, the most important reason is many methods (especially Redis commands) are attached at runtime, type hints for these methods are not available so that when people type `redis.get(key)`, TypeScript would complain about `#get()` doesn't exist on `redis`.

**Comment by xtianus79** [comment]
@luin has this been implemented yet?
